/**
 * REPORT COMMAND GROUP
 * Handles: /report generate
 * Generates a full formatted agent intelligence report.
 */

const { SlashCommandBuilder, EmbedBuilder, MessageFlags } = require('discord.js');
const db = require('../../modules/database');
const inv = require('../../modules/investigation');
const surv = require('../../modules/surveillance');
const perms = require('../../modules/permissions');
const { applyRateLimit } = require('../../modules/rateLimit');
const { paginate } = require('../../modules/pagination');
const config = require('../../modules/config');

const RISK_ICONS = { NONE: '⬜', LOW: '🟩', MEDIUM: '🟨', HIGH: '🟧', CRITICAL: '🟥' };
const STATUS_ICONS = { 'OPEN': '🟢', 'UNDER REVIEW': '🟡', 'CLOSED': '⬛' };

module.exports = {
  data: new SlashCommandBuilder()
    .setName('report')
    .setDescription('Generate intelligence reports')

    .addSubcommand(sub => sub
      .setName('generate')
      .setDescription('Generate a full intelligence report on a subject')
      .addUserOption(opt => opt.setName('user').setDescription('Subject to report on').setRequired(true))
    )
    .addSubcommand(sub => sub
      .setName('summary')
      .setDescription('Generate a network-wide threat summary')
    ),

  async execute(interaction) {
    if (!await applyRateLimit(interaction)) return;
    const sub = interaction.options.getSubcommand();

    // ── /report generate ──────────────────────────────────────────────────
    if (sub === 'generate') {
      if (!await perms.requireAccess(interaction, 'case.open')) return;

      const target = interaction.options.getUser('user');
      const profile = db.getProfile(target.id);

      if (!profile) {
        return interaction.reply({
          embeds: [new EmbedBuilder()
            .setColor(config.dangerColor)
            .setTitle(`${config.botName} // NO RECORD`)
            .setDescription(`\`\`\`\n[ ERROR ]\n> No profile found for \`${target.username}\`.\n> Use /profile create first.\n\`\`\``)
            .setTimestamp()
          ],
          flags: [MessageFlags.Ephemeral]
        });
      }

      const logData = surv.getUserLogs(target.id, 10);
      const allCases = Object.values(inv.getAllCases());
      const relatedCases = allCases.filter(c => c.assignedAgents.includes(target.id));

      const pages = [];

      // ── Page 1: Subject Overview ─────────────────────────────────────────
      pages.push(new EmbedBuilder()
        .setColor('#0d1b2a')
        .setTitle(`${config.botName} // INTELLIGENCE REPORT`)
        .setThumbnail(target.displayAvatarURL())
        .setDescription(
          `\`\`\`\n` +
          `╔══════════════════════════════════════╗\n` +
          `║     CLASSIFIED SUBJECT DOSSIER       ║\n` +
          `╚══════════════════════════════════════╝\n\n` +
          `  SUBJECT    : ${profile.username}\n` +
          `  DISCORD ID : ${profile.userId}\n` +
          `  RISK LEVEL : ${RISK_ICONS[profile.riskLevel]} ${profile.riskLevel}\n` +
          `  CLEARANCE  : ${perms.getRoleName(profile.clearance)}\n` +
          `  WATCHLIST  : ${profile.watchlisted ? '⚠️ ACTIVE' : 'INACTIVE'}\n` +
          `  FLAGS      : ${profile.flags.length}\n` +
          `  NOTES      : ${profile.notes.length}\n` +
          `  CASES      : ${relatedCases.length}\n` +
          `  CREATED    : ${new Date(profile.createdAt).toISOString().split('T')[0]}\n` +
          `  UPDATED    : ${new Date(profile.updatedAt).toISOString().split('T')[0]}\n` +
          `\`\`\``
        )
        .setFooter({ text: `Report generated by ${interaction.user.username} | SENTINEL NETWORK` })
        .setTimestamp()
      );

      // ── Page 2: Threat Assessment ─────────────────────────────────────────
      const flagLines = profile.flags.length > 0
        ? profile.flags.slice(-5).map((f, i) =>
            `  [${i + 1}] ${RISK_ICONS[f.level]} ${f.level} — ${f.reason || 'No reason'}`
          ).join('\n')
        : '  No flags on record.';

      const noteLines = profile.notes.length > 0
        ? profile.notes.slice(-3).map((n, i) =>
            `  [${i + 1}] ${n.text.substring(0, 65)}${n.text.length > 65 ? '...' : ''}`
          ).join('\n')
        : '  No notes on record.';

      pages.push(new EmbedBuilder()
        .setColor('#0d1b2a')
        .setTitle(`${config.botName} // THREAT ASSESSMENT`)
        .setDescription(
          `\`\`\`\n[ SECTION 2 — FLAGS & NOTES ]\n\n` +
          `  FLAGS (last 5):\n${flagLines}\n\n` +
          `  AGENT NOTES (last 3):\n${noteLines}\n\`\`\``
        )
        .setFooter({ text: `${target.username} | Page 2 | Sentinel Network` })
        .setTimestamp()
      );

      // ── Page 3: Case Involvement ──────────────────────────────────────────
      const caseLines = relatedCases.length > 0
        ? relatedCases.slice(-6).map(c =>
            `  ${STATUS_ICONS[c.status]} ${c.caseId} — ${c.title.substring(0, 30)}${c.title.length > 30 ? '...' : ''}`
          ).join('\n')
        : '  No case involvement found.';

      pages.push(new EmbedBuilder()
        .setColor('#0d1b2a')
        .setTitle(`${config.botName} // CASE INVOLVEMENT`)
        .setDescription(
          `\`\`\`\n[ SECTION 3 — CASE HISTORY ]\n\n` +
          `  Total cases assigned: ${relatedCases.length}\n\n` +
          `${caseLines}\n\`\`\``
        )
        .setFooter({ text: `${target.username} | Page 3 | Sentinel Network` })
        .setTimestamp()
      );

      // ── Page 4: Surveillance Log ──────────────────────────────────────────
      const eventLines = logData && logData.recentEvents.length > 0
        ? logData.recentEvents.map((e, i) => {
            const ts = new Date(e.timestamp).toISOString().replace('T', ' ').split('.')[0];
            return `  [${String(i + 1).padStart(2, '0')}] ${e.type}\n       ${ts}`;
          }).join('\n')
        : '  No surveillance events on record.';

      pages.push(new EmbedBuilder()
        .setColor('#0d1b2a')
        .setTitle(`${config.botName} // SURVEILLANCE LOG`)
        .setDescription(
          `\`\`\`\n[ SECTION 4 — RECENT ACTIVITY ]\n\n` +
          `  Watchlisted : ${logData?.watchlisted ? 'YES ⚠️' : 'NO'}\n` +
          `  Total Events: ${logData?.totalEvents || 0}\n\n` +
          `${eventLines}\n\`\`\``
        )
        .setFooter({ text: `${target.username} | Page 4 | CLASSIFIED — Handle with care` })
        .setTimestamp()
      );

      return paginate(interaction, pages);
    }

    // ── /report summary ───────────────────────────────────────────────────
    if (sub === 'summary') {
      if (!await perms.requireAccess(interaction, 'admin.audit')) return;

      const allProfiles = Object.values(db.getAllProfiles());
      const allCases = Object.values(inv.getAllCases());
      const watchlist = surv.getWatchlist();

      const riskOrder = { CRITICAL: 4, HIGH: 3, MEDIUM: 2, LOW: 1, NONE: 0 };
      const topThreats = allProfiles
        .filter(p => p.riskLevel !== 'NONE')
        .sort((a, b) => (riskOrder[b.riskLevel] || 0) - (riskOrder[a.riskLevel] || 0))
        .slice(0, 8)
        .map(p => `  ${RISK_ICONS[p.riskLevel]} ${p.username.padEnd(22)} ${p.riskLevel}`)
        .join('\n') || '  No flagged subjects.';

      const activeCases = allCases
        .filter(c => c.status !== 'CLOSED')
        .map(c => `  ${STATUS_ICONS[c.status]} ${c.caseId} — ${c.title.substring(0, 32)}`)
        .join('\n') || '  No active cases.';

      return interaction.reply({
        embeds: [new EmbedBuilder()
          .setColor('#0d1b2a')
          .setTitle(`${config.botName} // THREAT SUMMARY`)
          .setDescription(
            `\`\`\`\n` +
            `╔══════════════════════════════════════╗\n` +
            `║      NETWORK THREAT SUMMARY          ║\n` +
            `╚══════════════════════════════════════╝\n\n` +
            `  Generated : ${new Date().toUTCString()}\n` +
            `  Subjects  : ${allProfiles.length} profiled, ${watchlist.length} watched\n` +
            `  Cases     : ${allCases.filter(c => c.status !== 'CLOSED').length} active\n` +
            `\`\`\``
          )
          .addFields(
            {
              name: '🚨 THREAT ROSTER',
              value: `\`\`\`\n${topThreats}\n\`\`\``,
              inline: false
            },
            {
              name: '📁 ACTIVE INVESTIGATIONS',
              value: `\`\`\`\n${activeCases}\n\`\`\``,
              inline: false
            }
          )
          .setFooter({ text: `By ${interaction.user.username} | SENTINEL NETWORK — CLASSIFIED` })
          .setTimestamp()
        ]
      });
    }
  }
};
